=== PRihtarec/OTVRAC-Labos/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://or.fer.unizg.hr/bolesti.json",
    "type": "array",
    "title": "Skup bolesti",
    "description": "Skup podataka o bolestima za otvoreno računarstvo.",
    "items": {
      "type": "object",
      "title": "Bolest",
      "description": "Objekt koji sadrži informacije o jednoj bolesti.",
      "required": [
        "bolest_id",
        "naziv_bolesti",
        "simptomi",
        "tip_tretmana",
        "faktori_rizika",
        "razina_opasnosti",
        "uobicajeni_lijekovi",
        "dijagnosticki_testovi",
        "genetska_predispozicija",
        "brzina_progresije_bolesti",
        "tipicna_starost_dijagnoze"
      ],
      "properties": {
        "bolest_id": {
          "type": "integer",
          "title": "ID bolesti",
          "description": "Jedinstveni identifikator za svaku bolest"
        },
        "naziv_bolesti": {
          "type": "string",
          "title": "Naziv bolesti",
          "description": "Naziv bolesti."
        },
        "simptomi": {
          "type": "array",
          "title": "Simptomi",
          "description": "Lista simptoma povezanih s bolešću",
          "items": {
            "type": "string"
          }
        },
        "tip_tretmana": {
          "type": "string",
          "title": "Tip tretmana",
          "description": "Vrsta liječenja (medikamentozno, promjena načina života, terapija)"
        },
        "faktori_rizika": {
          "type": "string",
          "title": "Faktori rizika",
          "description": "Rizični čimbenici povezani s bolešću"
        },
        "razina_opasnosti": {
          "type": "string",
          "title": "Razina opasnosti",
          "description": "Razina ozbiljnosti bolesti (blaga, srednja, teška)"
        },
        "uobicajeni_lijekovi": {
          "type": "string",
          "title": "Uobičajeni lijekovi",
          "description": "Uobičajeni lijekovi propisani za liječenje bolesti"
        },
        "dijagnosticki_testovi": {
          "type": "string",
          "title": "Dijagnostički testovi",
          "description": "Uobičajeni dijagnostički testovi za potvrdu bolesti"
        },
        "genetska_predispozicija": {
          "type": "string",
          "title": "Genetska predispozicija",
          "description": "Genetska predispozicija povezana s bolešću (niska, srednja, visoka)"
        },
        "brzina_progresije_bolesti": {
          "type": "string",
          "title": "Brzina progresije bolesti",
          "description": "Stopa progresije bolesti"
        },
        "tipicna_starost_dijagnoze": {
          "type": "string",
          "title": "Tipična starost dijagnoze",
          "description": "Tipična dob dijagnosticiranja bolesti"
        }
      }
    }
  }

=== PRihtarec/OTVRAC-Labos/bolesti.json
[{"simptomi": ["Pojačana žeđ", "Često mokrenje", "Umor"], "bolest_id": 1, "tip_tretmana": "Lijekovi, promjene u načinu života", "naziv_bolesti": "Dijabetes", "faktori_rizika": "Pretilost, Sjedeći način života, Prehrana bogata šećerom", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "Inzulin, Metformin", "dijagnosticki_testovi": "Razina šećera u krvi, HbA1c", "genetska_predispozicija": "Umjerena do visoka", "brzina_progresije_bolesti": "Postupna, može se ubrzati ako se ne liječi", "tipicna_starost_dijagnoze": "Srednje odrasle do starije osobe"}, {"simptomi": ["Često asimptomatski", "Glavobolje", "Kratkoća daha"], "bolest_id": 2, "tip_tretmana": "Lijekovi, promjene u načinu života", "naziv_bolesti": "Hipertenzija", "faktori_rizika": "Visok unos soli, Pretilost, Stres", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "ACE inhibitori, Beta-blokatori", "dijagnosticki_testovi": "Mjerenja krvnog tlaka", "genetska_predispozicija": "Umjerena", "brzina_progresije_bolesti": "Postupna, može postati teška bez upravljanja", "tipicna_starost_dijagnoze": "Odrasli, obično preko 40"}, {"simptomi": ["Kratkoća daha", "Kronični kašalj", "Zviždanje pri disanju"], "bolest_id": 3, "tip_tretmana": "Lijekovi, izbjegavanje okidača", "naziv_bolesti": "Astma", "faktori_rizika": "Alergije, Izloženost pušenju, Zagađenje", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "Inhalacijski kortikosteroidi, Bronhodilatatori", "dijagnosticki_testovi": "Spirometrija, Mjerenje maksimalnog protoka", "genetska_predispozicija": "Visoka", "brzina_progresije_bolesti": "Varira; stabilno uz dobru kontrolu, epizodni izbijanja", "tipicna_starost_dijagnoze": "Djetinjstvo, ali može se javiti u bilo kojoj dobi"}, {"simptomi": ["Kratkoća daha", "Kronični kašalj"], "bolest_id": 4, "tip_tretmana": "Lijekovi, terapija kisikom", "naziv_bolesti": "Kronična opstruktivna plućna bolest", "faktori_rizika": "Pušenje, Izloženost prašini i kemikalijama", "razina_opasnosti": "Često teška i progresivna", "uobicajeni_lijekovi": "Bronhodilatatori, Steroidi", "dijagnosticki_testovi": "Testovi plućne funkcije, Rentgen prsnog koša", "genetska_predispozicija": "Niska, uglavnom zbog okolišnih faktora", "brzina_progresije_bolesti": "Postupna, ali progresivna ako se ne liječi", "tipicna_starost_dijagnoze": "Starije osobe, često preko 60"}, {"simptomi": ["Osjećaj stezanja u prsima", "Gubitak pamćenja"], "bolest_id": 5, "tip_tretmana": "Lijekovi, kognitivna terapija", "naziv_bolesti": "Alzheimerova bolest", "faktori_rizika": "Starost, Genetski faktori, Faktori načina života", "razina_opasnosti": "Progresivna, postaje teška", "uobicajeni_lijekovi": "Donepezil, Memantin", "dijagnosticki_testovi": "Kognitivne procjene, MRI skeniranje", "genetska_predispozicija": "Visoka za određene genske varijante", "brzina_progresije_bolesti": "Stabilno, ubrzava s vremenom", "tipicna_starost_dijagnoze": "Obično preko 65"}, {"simptomi": ["Zbunjenost", "Bolovi u zglobovima"], "bolest_id": 6, "tip_tretmana": "Lijekovi, promjene u prehrani", "naziv_bolesti": "Osteoporoza", "faktori_rizika": "Bolovi u kostima, Frakture", "razina_opasnosti": "Blaga do teška, ovisno o gustoći kostiju", "uobicajeni_lijekovi": "Bifosfonati, Suplementi kalcija", "dijagnosticki_testovi": "Skeniranje gustoće kostiju (DEXA)", "genetska_predispozicija": "Umjerena do visoka", "brzina_progresije_bolesti": "Postupna, povećava se s godinama", "tipicna_starost_dijagnoze": "Starije osobe, često postmenopauzalne"}, {"simptomi": ["Tremor"], "bolest_id": 7, "tip_tretmana": "Lijekovi, fizioterapija", "naziv_bolesti": "Reumatoidni artritis", "faktori_rizika": "Pušenje, Obiteljska povijest, Spol", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "Metotreksat, NSAID", "dijagnosticki_testovi": "Test za reumatoidni faktor, Rentgen zglobova", "genetska_predispozicija": "Visoka, posebno s određenim genetskim markerima", "brzina_progresije_bolesti": "Postupna, može dovesti do oštećenja zglobova ako se ne liječi", "tipicna_starost_dijagnoze": "Često odrasli od 30-50 godina"}, {"simptomi": ["Bolovi u trbuhu", "Ikterus"], "bolest_id": 8, "tip_tretmana": "Lijekovi, fizioterapija", "naziv_bolesti": "Parkinsonova bolest", "faktori_rizika": "Starost, Izloženost toksinima", "razina_opasnosti": "Progresivna, postaje teška", "uobicajeni_lijekovi": "Levodopa, Agonisti dopamina", "dijagnosticki_testovi": "Neurologijski pregled, MRI", "genetska_predispozicija": "Umjerena, pod utjecajem genetskih i okolišnih faktora", "brzina_progresije_bolesti": "Stabilno, često se ubrzava s vremenom", "tipicna_starost_dijagnoze": "Obično preko 60"}, {"simptomi": ["Kratkoća daha", "Bolovi u kostima"], "bolest_id": 9, "tip_tretmana": "Lijekovi, promjene u načinu života", "naziv_bolesti": "Koronarna arterijska bolest", "faktori_rizika": "Visok kolesterol, Pušenje, Hipertenzija", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "Statini, Beta-blokatori", "dijagnosticki_testovi": "EKG, Koronarna angiografija", "genetska_predispozicija": "Umjerena do visoka", "brzina_progresije_bolesti": "Postupna, povećava se s vremenom i lošim upravljanjem", "tipicna_starost_dijagnoze": "Srednje do starije osobe"}, {"simptomi": ["Bolovi u trbuhu", "Ikterus"], "bolest_id": 10, "tip_tretmana": "Lijekovi", "naziv_bolesti": "Hepatitis C", "faktori_rizika": "IV droga, Transfuzije krvi", "razina_opasnosti": "Blaga do teška", "uobicajeni_lijekovi": "Izravno djelujući antivirusni lijekovi (DAA)", "dijagnosticki_testovi": "Viralni teret, Testovi funkcije jetre", "genetska_predispozicija": "Niska, prvenstveno stečena izloženosti", "brzina_progresije_bolesti": "Varira, može postati kronična ako se ne liječi", "tipicna_starost_dijagnoze": "Često odrasli"}]
